### ISSUE TITLE
Flow's ViewAccessChecker has been replaced with NavigationAccessControl

### ISSUE THREAD

**Issue by heruan** [vaadin/sso-kit#130]
In Flow 24.3 `ViewAccessChecker` has been replaced with `NavigationAccessControl` and the method [`VaadinWebSecurity::getViewAccessChecker`](https://github.com/vaadin/flow/blob/225f964f4739b93dbca916920efdc9a534965944/vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java#L591-L595) has been marked deprecated and now throws a `UnsuppertedOperationException`.

To fix this we need to replace the call to `getViewAccessChecker()` with `getNavigationAccessControl()`.

**Comment by mcollovati** [comment]
VaadinWebSecurity implementation has been changed to be compatible with previous versions. The getViewAccessChecker method now returns a implementation that delegates to NavigationAccessControl.

A warning message is logged when the method is called.

Anyway, its usage should be replaced because the method will be removed in the future
