### ISSUE TITLE
Styling of Okta login page

### ISSUE THREAD

**Issue by heruan** [vaadin/sso-kit#19]
Part of #17

**Comment by DiegoCardoso** [comment]
Okta provides a few ways to customize the sign-in widget depending on which option the application using the provider chooses:

----
### Okta-hosted Sign-In Widget

On this case, the only option to customize the widget is through Okta's Admin Console. That leaves all the customization work to the admins of the Okta's instance. 
There are a few options to customize at **Customizations** > **Branding**:
![image](https://user-images.githubusercontent.com/262432/185944767-df267b09-83a1-411f-ba4a-0062cfd5a371.png)

The customizations done here are shared between all applications on the same Okta instance.

More customizations can be added on the built-in HTML editor at **Customizations** > **Sign-in page code editor**, like adding JS script to the sign-in page. This allows the developer to add per-application customization, since Okta provides a JS object `OktaUtil` that can be used to identify the application that triggered the sign-in page.

More can be found at the [Style the Okta-host Sign-In Widget](https://developer.okta.com/docs/guides/custom-widget/main/#style-the-okta-hosted-sign-in-widget) section.

**Our current prototype uses the Okta-hosted sign-in widget.**

----
### Self-hosted Sign-In Widget

This gives us more flexibility to add options on the addon so the developers can use them on their application. We could create, for instance, a component wrapping the widget and add the APIs for customizing its parameters, visual features and even its locatization to make it closer to what a developer is used to when working with a Vaadin application. This would require more work on our side to make sure the sign-in flow works as expected and create the right DX to make the component/view easily customizable. More info can be found at the [Style the Self-Hosted Sign-In Widget](https://developer.okta.com/docs/guides/custom-widget/main/#style-the-self-hosted-sign-in-widget) section. There might be necessary to tweak to the security configuration as well.
